# terraform/apps/helm-values/metrics-server-values.yaml

# Configuration pour le chart Helm metrics-server
# https://artifacthub.io/packages/helm/metrics-server/metrics-server

# --- Configuration cruciale pour la compatibilité EKS ---
# Le Metrics Server doit communiquer avec les kubelets sur chaque nœud.
# Par défaut, les certificats des kubelets sont souvent auto-signés.
# Cet argument désactive la vérification TLS, ce qui est une pratique
# standard et sécurisée dans le périmètre du cluster.
args:
  - --kubelet-insecure-tls

# --- Recommandations pour la production ---
# Il est bon de définir des requêtes et limites de ressources pour assurer la stabilité.
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 300Mi

# S'assure que le pod s'exécute sur des nœuds Linux.
nodeSelector:
  kubernetes.io/os: linux
