name: Checkov Scan

on:
push:
branches:
- main
- master
pull_request:
branches:
- main
- master

jobs:
scan:
runs-on: ubuntu-latest
steps:
# Step 1: Check out the repository
- name: Checkout repository
uses: actions/checkout@v3

# Step 2: Run Checkov
- name: Run Checkov
uses: bridgecrewio/checkov-action@v12
with:
output_format: cli,sarif
output_file_path: console,results.sarif

# Step 3: Upload SARIF results to GitHub Security tab
- name: Upload SARIF file
uses: github/codeql-action/upload-sarif@v2
if: success() || failure()
with:
sarif_file: results.sarif
