name: Checkov Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Exécuter Checkov
      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v11
        with:
          directory: ./terraform   # dossier Terraform à analyser
          output: checkov_report.json
          soft_fail: true          # le workflow continue même si des échecs
          quiet: false

      # Étape 3 : Upload du rapport JSON comme artefact
      - name: Upload Checkov JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: checkov_report.json
