name: IaC Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkov-scan:
    name: Checkov Terraform & JSON Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Checkov (Terraform & JSON)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          output_format: json
          skip_download: false
          quiet: false
        continue-on-error: true

      - name: Upload Checkov report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: checkov_report.json

  kubescape-scan:
    name: Kubescape Kubernetes YAML Scan
    runs-on: ubuntu-latest
    needs: checkov-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Kubescape Scan
        uses: kubescape/kubescape-action@v2
        with:
          args: scan framework nsa --exclude-namespaces kube-system -o json --output-file kubescape_report.json ./apps ./helm-values
        continue-on-error: true
      - name: Upload Kubescape report
        uses: actions/upload-artifact@v4
        with:
          name: kubescape-report
          path: kubescape_report.json
