name: Secret Scan (Gitleaks)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout le repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Exécuter Gitleaks via Marketplace
      - name: Run Gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          format: sarif          # Générer un rapport SARIF compatible GitHub
          output: gitleaks.sarif
          verbose: true
          redacted: false        # Pour ne pas masquer les secrets trouvés
          # Optional: chemin spécifique à scanner
          # path: "terraform/apps"

      # 3️⃣ Upload du rapport SARIF vers GitHub
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
