name: IaC Security Scan (Checkov)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checkov-scan:
    name: Run Checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Checkov (Terraform & Helm/K8s YAML)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true
          framework: terraform,kubernetes,helm
          soft_fail: true   # ✅ n'échoue pas le pipeline si des erreurs sont trouvées
          output_format: cli,sarif,json
          output_file_path: reports/checkov_report

      - name: Upload Checkov SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/checkov_report.sarif

      - name: Upload Checkov JSON report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-json-report
          path: reports/checkov_report.json
