name: Checkov Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Exécuter Checkov depuis le Marketplace
      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v11
        with:
          directory: ./  # dossier à analyser, ici le repo entier
          skip_check: ''  # aucun check ignoré
          quiet: false
          soft_fail: true  # NE PAS bloquer le workflow si des erreurs sont trouvées

      # Étape 3 : Optionnel, afficher le résumé
      - name: Display Checkov Report
        run: cat checkov_report.json || echo "No report generated"
