name: IaC Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkov-scan:
    name: Checkov Terraform & JSON Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Checkov scan (JSON report)
        uses: bridgecrewio/checkov-action@master   
        with:
          directory: .
          framework: kubernetes
          output_format: json
          output_file_path: ./checkov-report.json
          quiet: true
        continue-on-error: true

      - name: Upload Checkov JSON report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: ./checkov-report.json

  kubescape-scan:
    name: Kubescape Kubernetes YAML Scan
    runs-on: ubuntu-latest
    needs: checkov-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Kubescape Scan
        uses: kubescape/kubescape-action@main
        with:
          args: scan framework nsa --exclude-namespaces kube-system -o json --output-file kubescape_report.json ./apps ./helm-values
        continue-on-error: true
      - name: Upload Kubescape report
        uses: actions/upload-artifact@v4
        with:
          name: kubescape-report
          path: kubescape_report.json
