name: IaC Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
   k8s-manifest-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Checkov scan 
        uses: bridgecrewio/checkov-action@master   
        with:
          directory: .
          framework: kubernetes
          output_format: json
          output_file_path: ./checkov-report.json
          quiet: true
        continue-on-error: true

      - name: Upload Checkov JSON report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: ./checkov-report.json
