name: Security Scan with Checkov

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:

      - name: Run Checkov scan (JSON report)
        uses: bridgecrewio/checkov-action@master   
        with:
          directory: ./
          framework: "ALL"
          output_format: json
          output_file_path: ./checkov-report.json
        continue-on-error: true

      - name: Upload Checkov JSON report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: ./checkov-report.json
