name: Checkov Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Exécuter Checkov depuis le Marketplace
      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v11
        with:
          directory: ./          # dossier à analyser
          output: checkov_report.json  # nom du rapport JSON
          soft_fail: true         # ne bloque pas le workflow

      # Étape 3 : Upload du rapport JSON comme artefact
      - name: Upload Checkov Report
        uses: actions/upload-artifact@v3
        with:
          name: checkov-report
          path: checkov_report.json
