name: Security Scan with Checkov

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Lancer Checkov sur tout le dépôt
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v11
        with:
          directory: ./      # Analyse tout le repo
          framework: 'all'   # Terraform, Kubernetes, CloudFormation, etc.
        continue-on-error: true   # Ne bloque pas le pipeline si Checkov trouve des vulnérabilités
